"""a comment here

Revision ID: 160c5a3a5e11
Revises: 
Create Date: 2023-03-31 14:00:55.272218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160c5a3a5e11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('export_product_link', sa.String(length=255), nullable=True))
    op.drop_index('ix_platform_settings_access_token', table_name='platform_settings')
    op.drop_index('ix_platform_settings_api_id', table_name='platform_settings')
    op.drop_index('ix_platform_settings_api_secret', table_name='platform_settings')
    op.drop_index('ix_platform_settings_method_payment_id', table_name='platform_settings')
    op.drop_index('ix_platform_settings_platform_id', table_name='platform_settings')
    op.drop_index('ix_platform_settings_platform_url', table_name='platform_settings')
    op.drop_index('ix_platform_settings_referrer_id', table_name='platform_settings')
    op.drop_index('ix_platform_settings_shipping_profile_id', table_name='platform_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_platform_settings_shipping_profile_id', 'platform_settings', ['shipping_profile_id'], unique=False)
    op.create_index('ix_platform_settings_referrer_id', 'platform_settings', ['referrer_id'], unique=False)
    op.create_index('ix_platform_settings_platform_url', 'platform_settings', ['platform_url'], unique=False)
    op.create_index('ix_platform_settings_platform_id', 'platform_settings', ['platform_id'], unique=False)
    op.create_index('ix_platform_settings_method_payment_id', 'platform_settings', ['method_payment_id'], unique=False)
    op.create_index('ix_platform_settings_api_secret', 'platform_settings', ['api_secret'], unique=False)
    op.create_index('ix_platform_settings_api_id', 'platform_settings', ['api_id'], unique=False)
    op.create_index('ix_platform_settings_access_token', 'platform_settings', ['access_token'], unique=False)
    op.drop_column('platform_settings', 'export_product_link')
    # ### end Alembic commands ###
