"""payment

Revision ID: 203ce93afdfc
Revises: 
Create Date: 2023-03-24 14:29:36.332538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203ce93afdfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_method_id'), 'payment_method', ['id'], unique=False)
    op.create_index(op.f('ix_payment_method_name'), 'payment_method', ['name'], unique=True)
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.String(length=100), nullable=True),
    sa.Column('referrer_id', sa.String(length=100), nullable=True),
    sa.Column('api_id', sa.String(length=100), nullable=True),
    sa.Column('api_secret', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.String(length=100), nullable=True),
    sa.Column('platform_url', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_access_token'), 'platform_settings', ['access_token'], unique=False)
    op.create_index(op.f('ix_platform_settings_api_id'), 'platform_settings', ['api_id'], unique=False)
    op.create_index(op.f('ix_platform_settings_api_secret'), 'platform_settings', ['api_secret'], unique=False)
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.create_index(op.f('ix_platform_settings_name'), 'platform_settings', ['name'], unique=True)
    op.create_index(op.f('ix_platform_settings_platform_id'), 'platform_settings', ['platform_id'], unique=False)
    op.create_index(op.f('ix_platform_settings_platform_url'), 'platform_settings', ['platform_url'], unique=False)
    op.create_index(op.f('ix_platform_settings_referrer_id'), 'platform_settings', ['referrer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('payment_method_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('processor_params', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_method_vendor_id'), 'payment_method_vendor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_method_vendor_id'), table_name='payment_method_vendor')
    op.drop_table('payment_method_vendor')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_platform_settings_referrer_id'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_platform_url'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_platform_id'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_name'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_api_secret'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_api_id'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_access_token'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_payment_method_name'), table_name='payment_method')
    op.drop_index(op.f('ix_payment_method_id'), table_name='payment_method')
    op.drop_table('payment_method')
    # ### end Alembic commands ###
