"""copy paste

Revision ID: 27223135b1f2
Revises: 50706a8dce3d
Create Date: 2023-04-13 15:28:46.346821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27223135b1f2'
down_revision = '50706a8dce3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('mode', sa.String(length=25), nullable=False))
    op.add_column('permissions', sa.Column('model_name', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'permissions', ['name'])
    op.alter_column('user_permissions', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_permissions', 'permission_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_permissions', 'permission_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user_permissions', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_column('permissions', 'model_name')
    op.drop_column('permissions', 'mode')
    # ### end Alembic commands ###
